[profile.default]
src = 'src'
out = 'out'
libs = ['lib']
gas_reports = ["*"]
ffi = true

[profile.release]
optimizer = true
optimizer_runs = 20000


# See more config options https://github.com/gakonst/foundry/tree/master/config
